# Generated by Django 4.2.9 on 2024-01-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
    ]
