# Generated by Django 4.2.9 on 2024-01-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_address_post_code_birthcertificate_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='mobile',
            field=models.CharField(default='000000000', max_length=20),
        ),
    ]
